// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: user.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for UserService service

func NewUserServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for UserService service

type UserService interface {
	//add
	InserUser(ctx context.Context, in *InsertUserReq, opts ...client.CallOption) (*InsertUserRep, error)
	//delete
	DeleteUser(ctx context.Context, in *DeleteUerReq, opts ...client.CallOption) (*DeleteUserRep, error)
	//modify
	ModifyUser(ctx context.Context, in *ModifyUserReq, opts ...client.CallOption) (*ModifyUserRep, error)
	//select
	SelectUser(ctx context.Context, in *SelectUserReq, opts ...client.CallOption) (*SelectUserRep, error)
}

type userService struct {
	c    client.Client
	name string
}

func NewUserService(name string, c client.Client) UserService {
	return &userService{
		c:    c,
		name: name,
	}
}

func (c *userService) InserUser(ctx context.Context, in *InsertUserReq, opts ...client.CallOption) (*InsertUserRep, error) {
	req := c.c.NewRequest(c.name, "UserService.InserUser", in)
	out := new(InsertUserRep)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) DeleteUser(ctx context.Context, in *DeleteUerReq, opts ...client.CallOption) (*DeleteUserRep, error) {
	req := c.c.NewRequest(c.name, "UserService.DeleteUser", in)
	out := new(DeleteUserRep)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) ModifyUser(ctx context.Context, in *ModifyUserReq, opts ...client.CallOption) (*ModifyUserRep, error) {
	req := c.c.NewRequest(c.name, "UserService.ModifyUser", in)
	out := new(ModifyUserRep)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) SelectUser(ctx context.Context, in *SelectUserReq, opts ...client.CallOption) (*SelectUserRep, error) {
	req := c.c.NewRequest(c.name, "UserService.SelectUser", in)
	out := new(SelectUserRep)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for UserService service

type UserServiceHandler interface {
	//add
	InserUser(context.Context, *InsertUserReq, *InsertUserRep) error
	//delete
	DeleteUser(context.Context, *DeleteUerReq, *DeleteUserRep) error
	//modify
	ModifyUser(context.Context, *ModifyUserReq, *ModifyUserRep) error
	//select
	SelectUser(context.Context, *SelectUserReq, *SelectUserRep) error
}

func RegisterUserServiceHandler(s server.Server, hdlr UserServiceHandler, opts ...server.HandlerOption) error {
	type userService interface {
		InserUser(ctx context.Context, in *InsertUserReq, out *InsertUserRep) error
		DeleteUser(ctx context.Context, in *DeleteUerReq, out *DeleteUserRep) error
		ModifyUser(ctx context.Context, in *ModifyUserReq, out *ModifyUserRep) error
		SelectUser(ctx context.Context, in *SelectUserReq, out *SelectUserRep) error
	}
	type UserService struct {
		userService
	}
	h := &userServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&UserService{h}, opts...))
}

type userServiceHandler struct {
	UserServiceHandler
}

func (h *userServiceHandler) InserUser(ctx context.Context, in *InsertUserReq, out *InsertUserRep) error {
	return h.UserServiceHandler.InserUser(ctx, in, out)
}

func (h *userServiceHandler) DeleteUser(ctx context.Context, in *DeleteUerReq, out *DeleteUserRep) error {
	return h.UserServiceHandler.DeleteUser(ctx, in, out)
}

func (h *userServiceHandler) ModifyUser(ctx context.Context, in *ModifyUserReq, out *ModifyUserRep) error {
	return h.UserServiceHandler.ModifyUser(ctx, in, out)
}

func (h *userServiceHandler) SelectUser(ctx context.Context, in *SelectUserReq, out *SelectUserRep) error {
	return h.UserServiceHandler.SelectUser(ctx, in, out)
}
